spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: postgres
    password: faith
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8081

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: SXIvIL7Ze5DGsFrvnkVCsubZckxqb7Ee
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/